# Generated by Django 4.0.3 on 2022-05-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CienciaFiccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Terror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fecha_estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('sinopsis', models.CharField(max_length=200)),
            ],
        ),
    ]
