# Generated by Django 4.0.3 on 2022-05-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_peliss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='accion',
            name='sinopsis',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cienciaficcion',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cienciaficcion',
            name='sinopsis',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='comedia',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comedia',
            name='sinopsis',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='terror',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='terror',
            name='sinopsis',
            field=models.CharField(max_length=500),
        ),
    ]
