# Generated by Django 4.0.3 on 2022-05-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_peliss', '0002_alter_accion_name_alter_accion_sinopsis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='sinopsis',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='cienciaficcion',
            name='sinopsis',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='comedia',
            name='sinopsis',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='terror',
            name='sinopsis',
            field=models.CharField(max_length=1500),
        ),
    ]
